// stock-platform/frontend/src/pages/Rankings.jsx
import { useState, useEffect, useCallback } from 'react'
import { Link } from 'react-router-dom'
import { getRankings, refreshFull, getRefreshStatus } from '../api'

const TABS = [
  { key: 'score', label: '투자 점수 Top' },
  { key: 'value', label: '밸류 Top' },
  { key: 'growth', label: '성장 Top' },
]

function formatLastUpdated(iso) {
  if (!iso) return null
  try {
    return new Date(iso).toLocaleString('ko-KR', { dateStyle: 'short', timeStyle: 'short' })
  } catch {
    return iso
  }
}

export default function Rankings() {
  const [tab, setTab] = useState('score')
  const [data, setData] = useState([])
  const [lastRefreshAt, setLastRefreshAt] = useState(null)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)

  const load = useCallback(() => {
    setLoading(true)
    getRankings(tab, 50)
      .then(setData)
      .catch(() => setData([]))
      .finally(() => setLoading(false))
  }, [tab])

  useEffect(() => { load() }, [load])

  const handleRefresh = () => {
    setRefreshing(true)
    refreshFull()
      .then(() => {
        const poll = () => {
          getRefreshStatus()
            .then((st) => {
              if (st && st.running) {
                setTimeout(poll, 2000)
              } else {
                setLastRefreshAt(st?.last_completed_at ?? null)
                setRefreshing(false)
                load()
              }
            })
            .catch(() => {
              setRefreshing(false)
              load()
            })
        }
        poll()
      })
      .catch(() => {
        setRefreshing(false)
      })
  }

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex flex-wrap items-center gap-4 mb-4">
        <h1 className="text-2xl font-bold">종목 발견</h1>
        <button
          type="button"
          onClick={handleRefresh}
          disabled={refreshing || loading}
          className="px-4 py-2 rounded bg-blue-600 text-white disabled:opacity-50 disabled:cursor-not-allowed hover:bg-blue-700"
        >
          {refreshing ? '업데이트 중...' : '새로고침'}
        </button>
        {lastRefreshAt && (
          <span className="text-sm text-gray-500">마지막 업데이트: {formatLastUpdated(lastRefreshAt)}</span>
        )}
      </div>
      <div className="flex gap-2 mb-4">
        {TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`px-4 py-2 rounded ${tab === t.key ? 'bg-blue-600 text-white' : 'bg-gray-200'}`}
          >
            {t.label}
          </button>
        ))}
      </div>
      {loading ? (
        <p>로딩 중...</p>
      ) : (
        <ul className="space-y-2">
          {data.map((row, i) => (
            <li key={row.ticker} className="flex items-center gap-4 border-b py-2">
              <span className="text-gray-500 w-8">{i + 1}</span>
              <Link to={`/stock/${row.ticker}`} className="text-blue-600 font-medium hover:underline">
                {row.ticker}
              </Link>
              <span className="text-gray-700">
                {row.company_name}
                {row.company_name_ko ? <span className="text-gray-500 ml-1">({row.company_name_ko})</span> : null}
              </span>
              <span className="font-semibold">{row.score != null ? row.score.toFixed(1) : '-'}점</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// stock-platform/frontend-vue/src/pages/Rankings.vue
<template>
  <div class="space-y-6">
    <h1 class="text-2xl font-semibold text-gray-900 dark:text-gray-100">랭킹</h1>
    <div class="flex gap-2">
      <button v-for="tab in tabs" :key="tab.id" @click="activeTab = tab.id" class="rounded-lg px-4 py-2 text-sm font-medium transition-colors" :class="activeTab === tab.id ? 'bg-primary text-white' : 'bg-gray-100 dark:bg-surface-elevated text-neutral dark:text-gray-300'">{{ tab.label }}</button>
    </div>
    <div v-if="loading" class="flex min-h-[40vh] items-center justify-center">
      <div class="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent"></div>
    </div>
    <div v-else class="overflow-x-auto">
      <table class="w-full border-collapse">
        <thead>
          <tr class="border-b border-gray-200 dark:border-gray-600 text-left text-sm text-neutral dark:text-gray-400">
            <th class="p-3">순위</th>
            <th class="p-3">티커</th>
            <th class="p-3">회사명</th>
            <th class="p-3 text-right">점수</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(row, i) in list" :key="row.ticker" class="border-b border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-surface-elevated">
            <td class="p-3 text-gray-900 dark:text-gray-200">{{ i + 1 }}</td>
            <td class="p-3"><router-link :to="`/stock/${row.ticker}`" class="font-medium text-primary">{{ row.ticker }}</router-link></td>
            <td class="p-3 text-gray-900 dark:text-gray-200">{{ row.company_name }} <span v-if="row.company_name_ko" class="text-neutral dark:text-gray-400">({{ row.company_name_ko }})</span></td>
            <td class="p-3 text-right font-medium text-gray-900 dark:text-gray-200">{{ row.score != null ? Math.round(row.score) : '–' }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, onMounted } from 'vue'
import { getRankings } from '../services/api'

const tabs = [{ id: 'score', label: '투자점수' }, { id: 'value', label: '밸류' }, { id: 'growth', label: '성장' }]
const activeTab = ref('score')
const loading = ref(true)
const list = ref([])

async function fetchList() {
  loading.value = true
  try {
    list.value = await getRankings(activeTab.value, 50)
  } catch (e) {
    list.value = []
  } finally {
    loading.value = false
  }
}
onMounted(fetchList)
watch(activeTab, fetchList)
</script>
